language: java
jdk:
- openjdk11
script:
- mvn clean install
deploy:
  file:
  - "./deploy-key"
  provider: script
  script: deploy.sh
  on:
    all_branches: true
before_install:
- openssl aes-256-cbc -K $encrypted_60d2fc9a25e3_key -iv $encrypted_60d2fc9a25e3_iv -in deploy_key.enc -out deploy_key -d
